services:
  api:
    container_name: blog_api
    build:
      context: .
      dockerfile: ./docker/local/api/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./blog_api/:/app/
    env_file:
      - .env
    ports:
      - "${RAILS_PORT}:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    container_name: blog_db
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "${MYSQL_PORT}:3306"

volumes:
  db-data:

