services:
  api:
    build:
      context: .
      dockerfile: ./docker/local/api/Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./blog_api/:/app/
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
