services:
  nginx:
    container_name: blog_nginx
    build:
      context: .
      dockerfile: ./docker/local/nginx/Dockerfile
    env_file:
      - .env
    ports:
      - 80:80
  web:
    container_name: blog_web
    build:
      context: .
      dockerfile: ./docker/local/web/Dockerfile 
    command: yarn start
    volumes:
      - ./blog_web/:/app/
    env_file:
      - .env
    environment:
      REACT_APP_API_DOMEIN: ${REACT_APP_API_DOMEIN}
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
  api:
    container_name: blog_api
    build:
      context: .
      dockerfile: ./docker/local/api/Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3010 -b '0.0.0.0'"
    volumes:
      - ./blog_api/:/app/
    env_file:
      - .env
    environment:
      REDIS_URL: redis:6379
    ports:
      - 3010:3010
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    container_name: blog_db
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_ROOT_PASSWORD:  ${MYSQL_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
  
  mailhog:
    container_name: blog_mailhog
    image: mailhog/mailhog:latest
    platform: linux/amd64
    ports:
      - 8025:8025

  redis:
    container_name: blog_redis
    image: redis:7.2
    volumes:
      - redis-data:/var/lib/redis
    ports:
      - 6379:6379
volumes:
  db-data:
  redis-data:

