version: 2.1

orbs:
  fastly-cli: adobe/fastly-cli@1.1.1

jobs:
  purge-all-fastly:
    steps:
      machine:
        image: ubuntu-2204:2022.07.1
      - run:
          name: Wait 5 Sec
          command: sleep 5
      - fastly-cli
      # - run:
      #     name: Purge all Fastly
      #     command: fastly purge --all --service-id ${FASTLY_SERVICE_ID} -t ${FASTLY_API_TOKEN}

workflows:
  my-workflow:
    jobs:
      - purge-all-fastly
