version: 2.1

orbs:
  fastly-cli: adobe/fastly-cli@1.1.1

jobs:
  approval:
    type: approval
    approval_type: manual
    message: "Please approve the purge all for Fastly."

  purge-all-fastly:
    machine:
      image: ubuntu-2204:2024.11.1
    steps:
      - run:
          name: Wait 5 Sec
          command: sleep 5
      - fastly-cli/install
      - run:
          name: Purge all Fastly
          command: fastly purge --all --service-id ${FASTLY_SERVICE_ID} -t ${FASTLY_API_TOKEN}

workflows:
  version: 2
  my-workflow:
    jobs:
      - approval
          requires:
            - purge-all-fastly
      - purge-all-fastly
