# https://dev.classmethod.jp/articles/workflow-dispatch-fail-safe-by-inputs/
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'If you run flow, input "run".'
        required: true
        default: ''

jobs:
  purge-all-fastly:
    runs-on: ubuntu-latest
    steps:
      - name: Purge all Fastly
        run: echo "Purge all Fastly"
